/**
 * Zod-based request validation middleware (P0-1).
 *
 * Closes the biggest architectural gap identified in the engineering audit:
 * `@workspace/api-zod` ships 3,677 lines of orval-generated Zod schemas
 * covering 136 request shapes, but NO route in `src/routes/` imported or
 * invoked them. All 230 route handlers did hand-rolled
 * `if (!field) res.status(400).json(...)` validation (322 such calls),
 * with no compile-time body-shape safety and inconsistent error messages.
 *
 * This module provides three thin middleware factories:
 *
 *   - `validateBody(schema)`      — validates `req.body` against a Zod schema
 *   - `validateQuery(schema)`     — validates `req.query` against a Zod schema
 *   - `validateParams(schema)`    — validates `req.params` against a Zod schema
 *
 * On success, the validated (and coerced/transformed) value replaces the
 * corresponding field on `req`, so downstream handlers get fully-typed data.
 * On failure, the middleware responds with a 400 and a structured error
 * envelope that includes a `details` array of Zod issue paths — much more
 * useful for API consumers than the previous one-line `{ error: "..." }`.
 *
 * Schemas come from `@workspace/api-zod` (generated by orval from
 * `lib/api-spec/openapi.yaml`). To wire up a route:
 *
 *   ```ts
 *   import { CreateOrderBody } from "@workspace/api-zod";
 *   import { validateBody } from "../lib/validateRequest";
 *
 *   router.post("/orders", requireAuth, checkoutLimiter, validateBody(CreateOrderBody), async (req, res) => {
 *     // req.body is now fully typed as z.infer<typeof CreateOrderBody>
 *     ...
 *   });
 *   ```
 *
 * Error response shape (returned with status 400):
 *
 *   ```json
 *   {
 *     "error": "Validation failed",
 *     "details": [
 *       { "path": ["shippingAddress", "phone"], "message": "Required" },
 *       { "path": ["items", 0, "quantity"], "message": "Expected number, received string" }
 *     ]
 *   }
 *   ```
 *
 * Why a middleware (not a wrapper):
 *   The codebase's existing pattern is `router.METHOD(path, ...middleware,
 *   handler)`. A middleware composes naturally with `requireAuth`,
 *   `checkoutLimiter`, etc. without forcing a rewrite of every handler.
 *   Handlers stay async functions that read `req.body` / `req.query` /
 *   `req.params` exactly as before — just now with the runtime guarantee
 *   that those fields match the schema.
 */

import type { Request, Response, NextFunction } from "express";
import type { ZodTypeAny } from "zod";
import { logger } from "./logger";

/**
 * Format a Zod error's issue paths as dot/bracket notation strings for the
 * `details` array. E.g. `["shippingAddress", "phone"]` → `"shippingAddress.phone"`,
 * `["items", 0, "quantity"]` → `"items[0].quantity"`.
 */
function formatPath(path: (string | number)[]): string {
  if (path.length === 0) return "(root)";
  return path
    .map((p, i) => {
      if (typeof p === "number") return `[${p}]`;
      return i === 0 ? String(p) : `.${p}`;
    })
    .join("");
}

/**
 * Shared 400 responder. Logs the validation failure (so it shows up in
 * production logs for debugging) and returns a structured error envelope.
 */
function respondValidationError(
  res: Response,
  schemaName: string,
  issues: Array<{ path: (string | number)[]; message: string }>,
) {
  const details = issues.map((issue) => ({
    path: formatPath(issue.path),
    message: issue.message,
  }));
  logger.warn({ schemaName, details }, "Request validation failed");
  res.status(400).json({
    error: "Validation failed",
    details,
  });
}

/**
 * Middleware factory: validate `req.body` against a Zod schema.
 *
 * On success, replaces `req.body` with the parsed (and coerced) value.
 * On failure, responds 400 and halts the middleware chain.
 *
 * @param schema A Zod object schema (e.g. `CreateOrderBody` from `@workspace/api-zod`).
 * @param schemaName Human-readable name for logging (defaults to schema's inferred name).
 */
export function validateBody<T extends ZodTypeAny>(
  schema: T,
  schemaName = "body",
) {
  return async (req: Request, _res: Response, next: NextFunction) => {
    const result = schema.safeParse(req.body);
    if (!result.success) {
      respondValidationError(
        _res,
        schemaName,
        result.error.issues.map((issue) => ({
          path: issue.path,
          message: issue.message,
        })),
      );
      return;
    }
    // Replace req.body with the parsed (coerced/transformed) value so
    // downstream handlers get exactly what the schema produces — including
    // type coercions (e.g. string → number via z.coerce.number()) and
    // .transform() outputs.
    req.body = result.data;
    next();
  };
}

/**
 * Middleware factory: validate `req.query` against a Zod schema.
 *
 * Query params arrive as strings (from the URL), so schemas typically use
 * `z.coerce.number()`, `z.coerce.boolean()`, etc. to convert them.
 */
export function validateQuery<T extends ZodTypeAny>(
  schema: T,
  schemaName = "query",
) {
  return async (req: Request, _res: Response, next: NextFunction) => {
    const result = schema.safeParse(req.query);
    if (!result.success) {
      respondValidationError(
        _res,
        schemaName,
        result.error.issues.map((issue) => ({
          path: issue.path,
          message: issue.message,
        })),
      );
      return;
    }
    req.query = result.data as Record<string, unknown> as typeof req.query;
    next();
  };
}

/**
 * Middleware factory: validate `req.params` against a Zod schema.
 *
 * Path params arrive as strings, so schemas typically use
 * `z.coerce.number()` for numeric IDs.
 */
export function validateParams<T extends ZodTypeAny>(
  schema: T,
  schemaName = "params",
) {
  return async (req: Request, _res: Response, next: NextFunction) => {
    const result = schema.safeParse(req.params);
    if (!result.success) {
      respondValidationError(
        _res,
        schemaName,
        result.error.issues.map((issue) => ({
          path: issue.path,
          message: issue.message,
        })),
      );
      return;
    }
    req.params = result.data as Record<string, string> as typeof req.params;
    next();
  };
}
