-- ─── Migration 0010: Add embedding_model column for cross-model safety ───────
--
-- BUG-E1 critical fix: when the embedding model changed from
-- text-embedding-004 (shut down Jan 2026) to gemini-embedding-001,
-- existing document embeddings in ai_kb_entries were generated by the
-- OLD model. Query embeddings are now generated by the NEW model.
-- Cosine similarity between vectors from DIFFERENT models is meaningless
-- (the vector spaces are completely different) — the KB search was
-- returning garbage similarity scores for any entry embedded before
-- the migration.
--
-- This migration:
--   1. Adds an `embedding_model` TEXT column to track which model
--      generated each embedding.
--   2. Marks ALL existing embeddings as stale (embedding_status = 'pending',
--      embedding = NULL, embedding_model = NULL) so the background job
--      re-embeds them with the current model (gemini-embedding-001).
--
-- After re-embedding, the search SQL filters
-- `WHERE embedding_model = <current_model>` so stale embeddings (if any
-- remain from a future model change) are excluded from similarity
-- comparison — they fall back to keyword-only matching.
--
-- ─── Safety ──────────────────────────────────────────────────────────────────
--
-- All statements are idempotent (IF NOT EXISTS). Safe to re-run.
-- The UPDATE is safe: it only touches rows that HAVE an embedding but
-- DON'T have an embedding_model (i.e. pre-migration rows). Rows that
-- already have embedding_model set (post-migration) are untouched.
-- ────────────────────────────────────────────────────────────────────────────

-- 1. Add the embedding_model column (nullable — NULL means "unknown model").
ALTER TABLE ai_kb_entries
  ADD COLUMN IF NOT EXISTS embedding_model TEXT;

-- 2. Mark all existing embeddings as stale for re-embedding.
--    Any row with a non-NULL embedding but NULL embedding_model was
--    embedded by the old (text-embedding-004) model — its embedding
--    is in a different vector space than the current query embeddings.
--    We set embedding_status = 'pending', clear the embedding, and
--    set embedding_model = NULL so the background job picks them up.
UPDATE ai_kb_entries
  SET embedding_status = 'pending',
      embedding = NULL,
      embedding_model = NULL,
      embedding_error = NULL,
      updated_at = NOW()
  WHERE embedding IS NOT NULL
    AND embedding_model IS NULL;

-- 3. Index on embedding_model for fast filtering in the search query
--    (WHERE embedding_model = $N).
CREATE INDEX IF NOT EXISTS ai_kb_entries_embedding_model_idx
  ON ai_kb_entries (embedding_model)
  WHERE embedding_model IS NOT NULL;
