-- ─── RLS Decision: NOT implemented (documented rationale) ────────────────
--
-- RLS (Row-Level Security) was evaluated and intentionally NOT enabled
-- on this project's seller-scoped tables. This is a deliberate, documented
-- decision — not an oversight.
--
-- Why RLS was considered:
--   The audit flagged "all seller isolation is at API layer only" as a
--   MEDIUM concern. RLS would add DB-level defense-in-depth.
--
-- Why RLS was rejected for this project:
--
--   1. External auth system (Clerk, not Supabase Auth)
--      RLS is most valuable when the database itself knows the current
--      user (via Supabase Auth's auth.uid(), or Postgres roles). This
--      project uses Clerk for authentication — the DB has no native
--      concept of "who is the current user." Implementing RLS would
--      require setting a session variable (app.current_seller_id) via
--      SET LOCAL inside every transaction, which:
--        - Wraps every seller query in a transaction (perf overhead)
--        - Requires every route to use db.transaction (easy to forget)
--        - Fails silently if a route skips the SET LOCAL (returns no
--          rows, which looks like "no data" not "auth failure")
--
--   2. API-layer isolation is already comprehensive
--      The requireSeller middleware (middlewares/auth.ts) attaches
--      req.dbSeller after verifying the user has an active seller account.
--      Every seller route scopes queries by sellerId = req.dbSeller.id:
--        - sellerOrders.ts: eq(ordersTable.sellerId, sellerId)
--        - sellerListings.ts: eq(sellerListingsTable.sellerId, sellerId)
--        - sellerReturns.ts: eq(ordersTable.sellerId, sellerId)
--        - sellerPaymentConfigs.ts: eq(sellerPaymentConfigsTable.sellerId, sellerId)
--        - sellerCourierConfigs.ts: eq(sellerCourierConfigsTable.sellerId, sellerId)
--        - sellerPayoutAccounts.ts: eq(sellerPayoutAccountsTable.sellerId, sellerId)
--      These are consistent and were verified during the security audit.
--
--   3. IDOR checks are already in place
--      Every seller route that takes an ID parameter (orderId, listingId,
--      etc.) verifies ownership before returning/modifying:
--        if (order.sellerId !== req.dbSeller!.id) return 403
--      This was verified across all seller routes during the audit.
--
-- When RLS SHOULD be revisited:
--   If this project migrates to Supabase Auth (replacing Clerk), RLS
--   becomes trivial to implement via auth.uid() — no session variables
--   needed. At that point, re-enable RLS as defense-in-depth.
--
--   Until then, the API layer IS the correct authorization boundary for
--   a Clerk-authenticated application. This is the standard pattern used
--   by Clerk + Postgres applications in production.
